### ISSUE TITLE
 Invalid URL '': No schema supplied. Perhaps you meant http://?

### ISSUE THREAD

**Issue by burf2000** [faas-and-furious/inception-function#6]
So decided to get this working on my new MacBook Pro as can't get it to work on the server

## Expected Behaviour
URL=https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg \ echo $URL | faas-cli invoke inception

[{"name": "great white shark", "score": 0.5343291759490967}, {"name": "tiger shark", "score": 0.09276486188173294}, {"name": "grey whale", "score": 0.05899052694439888}, {"name": "sea lion", "score": 0.05105864629149437}, {"name": "hammerhead", "score": 0.019910583272576332}, {"name": "sturgeon", "score": 0.013177040033042431}, {"name": "stingray", "score": 0.00763126602396369}, {"name": "electric ray", "score": 0.006749240681529045}, {"name": "killer whale", "score": 0.005086909048259258}, {"name": "ice bear", "score": 0.003828041721135378}]

## Current Behaviour
URL=https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg 
echo $URL | faas-cli invoke inception
Server returned unexpected status code: 500 - exit status 1
Traceback (most recent call last):
  File "index.py", line 16, in <module>
    print(inception.invoke(st))
  File "/root/inception.py", line 570, in invoke
    image_path = download.maybe_download(body, data_dir)
  File "/root/download.py", line 70, in maybe_download
    download_local(url, file_path, agent)
  File "/root/download.py", line 79, in download_local
    r = requests.get(url, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

## Steps to Reproduce (for bugs)
Installed OpenFaas on local machine
Installed Inception via store
Ran Inception

## Your Environment
Docker 18.09.1, OSX 10.14.2 i7 2.5ghz
CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.11.1
 sha:     c394b09ae65177b3c6948b2c22b890068a8e6283
 commit:  Bump to nats-queue-worker 0.7.0

Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.6.1 
 sha:           3cac0ccc2e8bb7f567739a33f7d414cdb58440aa

**Comment by alexellis** [comment]
Try it like this:

```
export URL=https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg

echo $URL | faas-cli invoke inception
```

**Comment by burf2000** [comment]
I did as you suggested

```
export URL=https://upload.wikimedia.org/wikipedia/commons/6/61/Humpback_Whale_underwater_shot.jpg
echo $URL | faas-cli invoke inception
Server returned unexpected status code: 500 - exit status 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'File not found: '
	 [[{{node DecodeJpeg}} = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DecodeJpeg/contents_0_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 16, in <module>
    print(inception.invoke(st))
  File "/root/inception.py", line 575, in invoke
    pred = model.classify(image_path=image_path)
  File "/root/inception.py", line 343, in classify
    pred = self.session.run(self.y_pred, feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got unknown format starting with 'File not found: '
	 [[node DecodeJpeg (defined at /root/inception.py:242)  = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DecodeJpeg/contents_0_0)]]

Caused by op 'DecodeJpeg', defined at:
  File "index.py", line 16, in <module>
    print(inception.invoke(st))
  File "/root/inception.py", line 568, in invoke
    model = Inception()
  File "/root/inception.py", line 242, in __init__
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expected image (JPEG, PNG, or GIF), got unknown format starting with 'File not found: '
	 [[node DecodeJpeg (defined at /root/inception.py:242)  = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_DecodeJpeg/contents_0_0)]]
```

**Comment by burf2000** [comment]
Speech marks are needed around the url for the picture else you get an error

**Comment by rgee0** [comment]
Try:

`echo -n $URL | faas-cli invoke inception`
